// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ORM__Entity_Framework_Core_.DataModels;

namespace ORM__Entity_Framework_Core_.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.angajat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("data_adaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_angajare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_modificare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_nastere")
                        .HasColumnType("datetime2");

                    b.Property<int?>("departamentid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("id_departament")
                        .HasColumnType("int");

                    b.Property<int>("id_sector")
                        .HasColumnType("int");

                    b.Property<int>("numar")
                        .HasColumnType("int");

                    b.Property<string>("nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("salariu")
                        .HasColumnType("int");

                    b.Property<int?>("sectorid")
                        .HasColumnType("int");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("strada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("departamentid");

                    b.HasIndex("sectorid");

                    b.ToTable("Angajat");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.angajat_proiect", b =>
                {
                    b.Property<int>("id_angajat")
                        .HasColumnType("int");

                    b.Property<int>("id_proiect")
                        .HasColumnType("int");

                    b.Property<int?>("angajatid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data_adaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_modificare")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("nr_ore_saptamana")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("proiectid")
                        .HasColumnType("int");

                    b.HasKey("id_angajat", "id_proiect");

                    b.HasIndex("angajatid");

                    b.HasIndex("proiectid");

                    b.ToTable("AngajatProiect");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.departament", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("data_adaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_modificare")
                        .HasColumnType("datetime2");

                    b.Property<string>("denumire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Departament");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.partenerAngajat", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("angajatid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data_adaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_modificare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("id_angajat")
                        .HasColumnType("int");

                    b.Property<string>("nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prenume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sex")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("angajatid");

                    b.ToTable("PartenerAngajat");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.proiect", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("buget")
                        .HasColumnType("int");

                    b.Property<string>("cod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("data_adaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_incepere")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_modificare")
                        .HasColumnType("datetime2");

                    b.Property<int?>("departamentid")
                        .HasColumnType("int");

                    b.Property<int>("id_departament")
                        .HasColumnType("int");

                    b.Property<string>("nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("termen_limita")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("departamentid");

                    b.ToTable("Proiect");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.sector", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("cod_postal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("data_adaugare")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("data_modificare")
                        .HasColumnType("datetime2");

                    b.Property<string>("denumire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Sector");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.angajat", b =>
                {
                    b.HasOne("ORM__Entity_Framework_Core_.DataModels.departament", "departament")
                        .WithMany("angajats")
                        .HasForeignKey("departamentid");

                    b.HasOne("ORM__Entity_Framework_Core_.DataModels.sector", "sector")
                        .WithMany("angajats")
                        .HasForeignKey("sectorid");

                    b.Navigation("departament");

                    b.Navigation("sector");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.angajat_proiect", b =>
                {
                    b.HasOne("ORM__Entity_Framework_Core_.DataModels.angajat", "angajat")
                        .WithMany("angajat_proiect")
                        .HasForeignKey("angajatid");

                    b.HasOne("ORM__Entity_Framework_Core_.DataModels.proiect", "proiect")
                        .WithMany("angajat_proiect")
                        .HasForeignKey("proiectid");

                    b.Navigation("angajat");

                    b.Navigation("proiect");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.partenerAngajat", b =>
                {
                    b.HasOne("ORM__Entity_Framework_Core_.DataModels.angajat", "angajat")
                        .WithMany("partenerAngajats")
                        .HasForeignKey("angajatid");

                    b.Navigation("angajat");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.proiect", b =>
                {
                    b.HasOne("ORM__Entity_Framework_Core_.DataModels.departament", "departament")
                        .WithMany("proiects")
                        .HasForeignKey("departamentid");

                    b.Navigation("departament");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.angajat", b =>
                {
                    b.Navigation("angajat_proiect");

                    b.Navigation("partenerAngajats");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.departament", b =>
                {
                    b.Navigation("angajats");

                    b.Navigation("proiects");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.proiect", b =>
                {
                    b.Navigation("angajat_proiect");
                });

            modelBuilder.Entity("ORM__Entity_Framework_Core_.DataModels.sector", b =>
                {
                    b.Navigation("angajats");
                });
#pragma warning restore 612, 618
        }
    }
}
